export const motivationalQuotes = {
  uk: [
    "Успіх - це сума маленьких зусиль, що повторюються день за днем. 💪",
    "Не чекай ідеального моменту. Візьми момент і зроби його ідеальним. ✨",
    "Твоє майбутнє створюється тим, що ти робиш сьогодні, а не завтра. 🚀",
    "Кожен день - це нова можливість стати кращою версією себе. 🌟",
    "Маленькі кроки щодня ведуть до великих змін. 👣",
    "Дисципліна - це міст між цілями та досягненнями. 🌉",
    "Ти сильніший, ніж думаєш, і здатний на більше, ніж уявляєш. 💎",
    "Прогрес, а не досконалість - ось що має значення. 📈",
    "Кожна звичка - це голос за тип людини, якою ти хочеш стати. 🗳️",
    "Не зупиняйся, коли втомився. Зупинись, коли закінчиш. 🏁",
  ],
  en: [
    "Success is the sum of small efforts repeated day in and day out. 💪",
    "Don't wait for the perfect moment. Take the moment and make it perfect. ✨",
    "Your future is created by what you do today, not tomorrow. 🚀",
    "Every day is a new opportunity to become a better version of yourself. 🌟",
    "Small steps daily lead to big changes yearly. 👣",
    "Discipline is the bridge between goals and accomplishment. 🌉",
    "You are stronger than you think and capable of more than you imagine. 💎",
    "Progress, not perfection, is what matters. 📈",
    "Every habit is a vote for the type of person you wish to become. 🗳️",
    "Don't stop when you're tired. Stop when you're done. 🏁",
  ],
};